config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



 namespace :admin do
    get '/' => 'homes#top'
    patch '/order_details/' => 'order_details#update'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# get '/customers/is_deleted' => 'public/customers#is_deleted'
namespace :public, path: "" do
  get "search" => "searches#search"
  get '/customers/my_page' => 'customers#show'
  get '/customers/is_deleted' => 'customers#is_deleted'
  patch '/customers/withdraw' => 'customers#withdraw'
  get '/' => 'homes#top'
  get '/about' => 'homes#about'
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :customers, only: [:edit, :update]
  resources :items, only: [:index, :show]
  resources :send_addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :send_addresses


  validates :first_name, :familly_name, :first_name_kana, :familly_name_kana,
            :address, :telephone_number, :zipcode,
            presence: true
  validates :zipcode, length: {is: 7}, numericality: { only_integer: true }
  validates :telephone_number, numericality: { only_integer: true }
  validates :first_name_kana, :familly_name_kana,
      format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "カタカナで入力して下さい。"}

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def customer_delivery
    "〒" + self.zipcode + " " + self.address + " " + self.familly_name + " " + self.first_name
  end

  def full_name
    self.familly_name + "　" + self.first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

def index
  @customers=Customer.all
  @customers=Customer.all.page(params[:page]).per(10)
end

def show
  @customers = Customer.all
  @customer = Customer.find(params[:id])
end

def edit
  @customer = Customer.find(params[:id])
  @customers = Customer.all
end

def update
  @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
    redirect_to admin_customers_path
  else
    @customers = Customer.all
    render "edit"
  end
end



  def customer_params
    params.require(:customer).permit(:familly_name, :first_name, :familly_name_kana, :first_name_kana,
    :zipcode, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="row">
  <div class="offset-1">
    <h4><%= @customer.familly_name %><%= @customer.first_name %>さんの会員情報編集</h4>
  </div>
</div>



<div class='container px-10'>
  <div class="row">
    <div class="col">

<%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>

      <table>

        <div class="row">
          <div class="col-2 mt-5">会員ID</div>
          <div class="mx-3 mt-5"><%= @customer.id %>
          </div>
        </div>

        <div class="row">
          <div class="col-2 mt-4">氏名</div>
          <div class="col-3 mx-1 mt-4"><%= f.text_field :familly_name, autofocus: true, id:"familly_name", placeholder:"氏名", class: "form-control" %></div>
          <div class="col-3 mx-1 mt-4"><%= f.text_field :first_name, autofocus: true, id:"first_name", placeholder:"氏名", class: "form-control" %></div>
        </div>

        <div class="row">
          <div class="col-2 mt-4">フリガナ</div>
          <div class="col-3 mx-1 mt-4"><%= f.text_field :familly_name_kana, autofocus: true, id:"familly_name_kana", placeholder:"フリガナ", class: "form-control" %></div>
          <div class="col-3 mx-1 mt-4"><%= f.text_field :first_name_kana, autofocus: true, id:"first_name_kana", placeholder:"フリガナ", class: "form-control" %></div>
        </div>

        <div class="row">
          <div class="col-2 mt-4">郵便番号</div>
          <div class="col-3 mx-1 mt-4"><%= f.text_field :zipcode, autofocus: true, id:"zipcode", placeholder:"郵便番号", class: "form-control" %></div>
        </div>

        <div class="row">
          <div class="col-2 mt-4">住所</div>
          <div class="col-8 mx-1 mt-4"><%= f.text_field :address, autofocus: true, id:"address", placeholder:"住所", class: "form-control" %></div>
        </div>

        <div class="row">
          <div class="col-2 mt-4">電話番号</div>
          <div class="col-3 mx-1 mt-4"><%= f.text_field :telephone_number, autofocus: true, id:"telephon_number", placeholder:"電話番号", class: "form-control" %></div>
        </div>

        <div class="row">
          <div class="col-2 mt-4">メールアドレス</div>
          <div class="col-3 mx-1 mt-4"><%= f.text_field :email, autofocus: true, id:"email", placeholder:"メールアドレス", class: "form-control" %></div>
        </div>

        <div class="row">
          <div class="col-2 mt-4">退会ステータス</div>
          <div class="col-3 mx-1 mt-4">
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "退会　　" %>
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "有効" %>
          </div>
        </div>

    <div class="row">
      <div class="col-2 mt-4"></div>
        <div class="col-3 mt-4 btn-lg">
          <strong><%= f.submit "変更を保存", class: 'btn btn-success btn-lg '%></strong>
      </div>
    </div>

    <%end%>
      </table>
      </div>
    </div>
  </div>

app/views/admin/customers/index.html.erb
 <div class="row">
   <div class="offset-2"><h4>会員一覧</h4></div>
 </div>


    <div class="col-lg-8 offset-2 mt-3">
    <table class="table">
      <thead class="table-secondary">
        <tr>
          <th width="20%">会員ID</th>
          <th width="30%">氏名</th>
          <th width="30%">メールアドレス</th>
          <th width="20%">ステータス</th>
        </tr>
      </thead>
  <% @customers.each do |customer| %>
    <tbody>
      <div class="h-50">
      <tr>
        <td><%= customer.id%></td>
        <td>
          <%= link_to admin_customer_path(customer) do%>
          <%= customer.familly_name%><%= customer.first_name%>
          <%end%>
        </td>
        <td><%= customer.email%></td>
        <td><% if customer.is_deleted == true %>
            <p class="text-secondary mt-3"><strong>退会</strong></p>
            <%else%>
      　     <p class="text-success"><strong>有効</strong></p>
            <%end%>
        </td>
      </tr>
      </div>
  <%end%>
    </tbody>
    </table>
    </div>

      <div class="row">
        <div class="offset-5">
          <div class="text-center"><%= paginate @customers %></div>
        </div>
      </div>

app/views/admin/customers/show.html.erb
<div class="row">
  <div class="offset-1">
    <h4><%= @customer.familly_name %><%= @customer.first_name %>さんの会員詳細</h4>
  </div>
</div>

<div class='container'>
<table class="table table-borderless">

    <div class="mt-5"></div>

      <tr>
        <td width="20%">会員ID</td>
        <td><%= @customer.id %></td>
      </tr>

      <tr>
        <td>氏名</td>
        <td><%= @customer.familly_name %><%= @customer.first_name %></td>
      </tr>

      <tr>
        <td>フリガナ</td>
        <td><%= @customer.familly_name_kana %><%= @customer.first_name_kana %></td>
      </tr>

      <tr>
        <td>郵便番号</td>
        <td><%= @customer.zipcode %></td>
      </tr>

      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>

      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>

      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>

      <tr>
        <td>会員ステータス</td>
        <td><% if @customer.is_deleted == true %><p class="text-secondary"><strong>退会済み</strong></p>
            <%else%> <p class="text-success"> <strong>有効</strong></p>
            <%end%>
        </td>
      </tr>
</table>
</div>
<div class="row">
  <div class="offset-3">
    <div class="col-12 mx-4">
    <%=link_to "編集する", edit_admin_customer_path(@customer), class: 'btn btn-success ' %>
    <%=link_to "注文履歴一覧を見る", admin_path(@customers), class: 'btn btn-primary ml-5' %>
    </div>
  </div>
  </div>