config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



 namespace :admin do
    get '/' => 'homes#top'
    patch '/order_details/' => 'order_details#update'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
  end

# get '/customers/is_deleted' => 'public/customers#is_deleted'
namespace :public, path: "" do
  get "search" => "searches#search"
  get '/customers/my_page' => 'customers#show'
  get '/customers/is_deleted' => 'customers#is_deleted'
  patch '/customers/withdraw' => 'customers#withdraw'
  get '/' => 'homes#top'
  get '/about' => 'homes#about'
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/complete' => 'orders#complete'
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :customers, only: [:edit, :update]
  resources :items, only: [:index, :show]
  resources :send_addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :cart_items, only: [:index, :update, :destroy, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :send_addresses


  validates :first_name, :familly_name, :first_name_kana, :familly_name_kana,
            :address, :telephone_number, :zipcode,
            presence: true
  validates :zipcode, length: {is: 7}, numericality: { only_integer: true }
  validates :telephone_number, numericality: { only_integer: true }
  validates :first_name_kana, :familly_name_kana,
      format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: "カタカナで入力して下さい。"}

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def customer_delivery
    "〒" + self.zipcode + " " + self.address + " " + self.familly_name + " " + self.first_name
  end

  def full_name
    self.familly_name + "　" + self.first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
  belongs_to :genre
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true, length: {maximum: 200}
  validates :price, presence: true



  def get_image
    if image.attached?
      image
    else
      'logo.png'
    end
  end

  def add_tax_price
    (self.price * 1.10).round
  end

  def self.looks(search, word)
    Item.where("name LIKE?","%#{word}%")
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting: 0, confirm: 1, making: 2, preparing: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { unavailable: 0, waiting: 1, making: 2, complete: 3 }
end

app/models/send_address.rb
class SendAddress < ApplicationRecord
  belongs_to :customer

  validates :name, :address, :zipcode,
            presence: true
  validates :zipcode, length: {is: 7}, numericality: { only_integer: true }

  def full_deliveries
    "〒" + self.zipcode + " " + self.address + " " + self.name
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to request.referer
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
        redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render "new"
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      @genres = Genre.all
      render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      public_path
    end
  end
  # end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
    when :customer
      new_customer_session_path
    end
  end
  #   root_path
  # end


  protected

  #顧客側登録時のストロングパラメータ

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :familly_name, :first_name_kana, :familly_name_kana, :zipcode, :address, :telephone_number])

  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item">
        <%= link_to public_path, class: "nav-link px-2 text-muted" do %>Home<% end %>
      </li>
      <li class="nav-item">
        <%= link_to public_about_path, class: "nav-link px-2 text-muted" do %>About<% end %>
      </li>
      <li class="nav-item">
        <%= link_to public_items_path, class: "nav-link px-2 text-muted" do %>Items<% end %>
      </li>
    </ul>
  <p class="text-center text-muted"><%= link_to new_admin_session_path, class: "text-decoration-none text-muted" do %>©<% end %> 2022 Nagano Cake, Team TOFU</p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgba(153, 204, 0, 0.3);">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><%= image_tag('logo.png') %></a>

        <span class="navbar-text text-secondary">
         <strong> <% if customer_signed_in? %> ようこそ<%= current_customer.familly_name %>さん <% elsif admin_signed_in? %> 管理者 <% else %> いらっしゃいませ <% end %></strong>
        </span>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>
          <li>
            <%= link_to '/customers/my_page',class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">マイページ</button>
            <% end %>
          </li>
          <li>
            <%=  link_to public_items_path,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">商品一覧</button>
            <% end %>
          </li>
          <li>
            <%=  link_to public_cart_items_path,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">カート</button>
            <% end %>
          </li>
          <li>

            <%= link_to  '/customers/sign_out', method: :delete,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">ログアウト</button>
            <% end %>
          </li>

        <% elsif admin_signed_in? %>
           <li>
            <%= link_to admin_items_path,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">商品一覧</button>
            <% end %>
          </li>
          <li>
            <%=  link_to admin_customers_path,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">会員一覧</button>
            <% end %>
          </li>
          <li>
            <%=  link_to admin_path,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">注文履歴一覧</button>
            <% end %>
          </li>
          <li>
            <%=  link_to admin_genres_path,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">ジャンル一覧</button>
            <% end %>
          </li>
          <li>

            <%= link_to  '/admin/sign_out', method: :delete,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">ログアウト</button>
            <% end %>
          </li>

        <% else %>
          <li>
            <%= link_to'/about',class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">About</button>
            <% end %>
          </li>
          <li>
            <%= link_to public_items_path,class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">商品一覧</button>
            <% end %>
          </li>
          <li>
            <%= link_to '/customers/sign_up',class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">新規登録</button>
            <% end %>
          </li>
          <li>
            <%= link_to '/customers/sign_in',class: 'nav-link text-light' do %>
              <button type="button" class="btn btn-outline-success">ログイン</button>
            <% end %>
          </li>
        <% end %>
        </ul>
        <!-- 検索機能 -->

            <%= form_with url: public_search_path, local: true, method: :get, class: "d-flex ml-5" do |f| %>
              <%= f.search_field :word, placeholder:"商品名で検索", class: "form-control me-2"%>
              <%= f.submit "検索", class: "btn btn-outline-success ml-1" %>
            <% end %>



      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <div class="text-center mx-auto"><p id="notice"><%= notice %></p></div>
        <%= yield %>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>